In [1]:
import pandas as pd
import pandas_datareader as pdr
import urllib.request as ur
from bs4 import BeautifulSoup as soup
import numpy as np
import pandas_datareader as pdr

C:\Users\PC\anaconda3\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [3]:
#collecting html from yahoo world indices website
html_1=ur.urlopen('https://finance.yahoo.com/world-indices/')
html_ticker=html_1.read().decode('utf8')
html_1.close()
#extracting global ticker using bs4
raw_html=soup(html_ticker)
table=raw_html.table.find_all('td')
for td in table:
    print(td.text)

^GSPC
S&P 500
3,306.51
+11.90
+0.36%
2.389B



^DJI
Dow 30
26,828.47
+164.07
+0.62%
346.347M



^IXIC
Nasdaq
10,941.17
+38.37
+0.35%
3.675B



^NYA
NYSE COMPOSITE (DJ)
12,612.11
+75.30
+0.60%
0



^XAX
NYSE AMEX COMPOSITE INDEX
2,128.27
+55.34
+2.67%
0



^BUK100P
Cboe UK 100 Price Return
600.63
-0.87
-0.15%
0



^RUT
Russell 2000
1,517.21
+10.41
+0.69%
0



^VIX
Vix
23.79
-0.49
-2.02%
0



^FTSE
FTSE 100
6,036.00
+3.15
+0.05%
0



^GDAXI
DAX PERFORMANCE-INDEX
12,600.87
-46.11
-0.36%
0



^FCHI
CAC 40
4,889.52
+13.59
+0.28%
0



^STOXX50E
ESTX 50 PR.EUR
3,254.29
+6.01
+0.19%
0



^N100
EURONEXT 100
973.30
+1.99
+0.20%
0



^BFX
BEL 20
3,320.71
-2.28
-0.07%
0



IMOEX.ME
MOEX Russia Index
2,940.46
+10.49
+0.36%
0



^N225
Nikkei 225
22,573.66
+378.28
+1.70%
0



^HSI
HANG SENG INDEX
24,946.63
+488.50
+2.00%
0



000001.SS
SSE Composite Index
3,371.69
+3.72
+0.11%
1.283B



399001.SZ
Shenzhen Component
13,860.46
-104.10
-0.75%
1.518B



^STI
STI Index
2,515.70
+30.79
+1.24%
0



^AXJO
S&P/ASX 200
6,037.60
+111.50
+1.88%
0



^AORD
ALL ORDINARIES
6,166.50
+112.60
+1.86%
0



^BSESN
S&P BSE SENSEX
37,687.91
+748.31
+2.03%
0



^JKSE
Jakarta Composite Index
5,075.00
+68.78
+1.37%
0



^KLSE
FTSE Bursa Malaysia KLCI
1,575.94
+3.33
+0.21%
0



^NZ50
S&P/NZX 50 INDEX GROSS
11,771.72
+105.63
+0.91%
0



^KS11
KOSPI Composite Index
2,279.97
+28.93
+1.29%
722,906



^TWII
TSEC weighted index
12,709.92
+196.89
+1.57%
0



^GSPTSE
S&P/TSX Composite index
16,368.03
+198.83
+1.23%
240.902M



^BVSP
IBOVESPA
101,181.83
-1,648.13
-1.60%
0



^MXX
IPC MEXICO
37,426.42
-120.30
-0.32%
181.917M



^IPSA
S&P/CLX IPSA
5,058.88
0.00
0.00%
0



^MERV
MERVAL
38,390.84
+233.89
+0.61%
0



^TA125.TA
TA-125
1,397.09
+7.85
+0.57%
0



^CASE30
EGX 30 Price Return Index
10,620.10
+20.60
+0.19%
329.557M



^JN0U.JO
Top 40 USD Net TRI Index
3,206.46
-7.71
-0.24%
0

In [4]:
#extracting global ticker using pandas
pd_html=pd.read_html('https://finance.yahoo.com/world-indices/',header=0)
for tab in pd_html:
    ticker=pd.DataFrame(tab)
    continue

In [5]:
tickers=np.array(list(ticker['Symbol']))
tickers

array(['^GSPC', '^DJI', '^IXIC', '^NYA', '^XAX', '^BUK100P', '^RUT',
       '^VIX', '^FTSE', '^GDAXI', '^FCHI', '^STOXX50E', '^N100', '^BFX',
       'IMOEX.ME', '^N225', '^HSI', '000001.SS', '399001.SZ', '^STI',
       '^AXJO', '^AORD', '^BSESN', '^JKSE', '^KLSE', '^NZ50', '^KS11',
       '^TWII', '^GSPTSE', '^BVSP', '^MXX', '^IPSA', '^MERV', '^TA125.TA',
       '^CASE30', '^JN0U.JO'], dtype='<U9')

In [6]:
#missing tickers data in yahoo finance ^FTSE','^STI',^KLSE
unavailable=['^KLSE','^FTSE','^STI']
#removing missing tickers
for item in unavailable:
    tickers=tickers[tickers!=item]
tickers

array(['^GSPC', '^DJI', '^IXIC', '^NYA', '^XAX', '^BUK100P', '^RUT',
       '^VIX', '^GDAXI', '^FCHI', '^STOXX50E', '^N100', '^BFX',
       'IMOEX.ME', '^N225', '^HSI', '000001.SS', '399001.SZ', '^AXJO',
       '^AORD', '^BSESN', '^JKSE', '^NZ50', '^KS11', '^TWII', '^GSPTSE',
       '^BVSP', '^MXX', '^IPSA', '^MERV', '^TA125.TA', '^CASE30',
       '^JN0U.JO'], dtype='<U9')

In [7]:
#extracting data
start="2002-01-01"
end = "2020-06-30"
raw_data={}
for code in tickers:
    try:
        raw_data['{}'.format(code)]=pdr.get_data_yahoo(code,start,end)
    except KeyError:
        pass

In [ ]:
#for i in raw_data.keys():
    #raw_data[i].to_csv('C:\\Users\\PC\\Desktop\\Thesis\\database\\thesis_data\\{file}.csv'.format(file=i))

In [8]:
#dataframe containing adj closing price of all tickers
master_data=pd.DataFrame(index=raw_data['^GSPC'].index)
for column in raw_data.keys():
    master_data[column]=raw_data[column]['Adj Close']

In [9]:
#save as csv master data
#master_data.to_csv('C:\\Users\\PC\\Desktop\\Thesis\\database\\thesis_data\\master_data.csv')
#master_data=pd.read_csv('C:\\Users\\PC\\Desktop\\Thesis\\database\\thesis_data\\master_data.csv',index_col='Date')
master_data

,^GSPC,^DJI,^IXIC,^NYA,^XAX,^BUK100P,^RUT,^VIX,^GDAXI,^FCHI,...,^NZ50,^KS11,^TWII,^GSPTSE,^BVSP,^MXX,^IPSA,^MERV,^TA125.TA,^JN0U.JO
Date,,,,,,,,,,,,,,,,,,,,,
2002-01-02,1154.670044,10073.400391,1979.250000,6244.209961,843.750000,NaN,487.190002,22.709999,5167.879883,4580.439941,...,NaN,724.950012,5600.028809,7646.799805,13872.0,6410.049805,1185.750000,323.690002,464.250000,NaN
2002-01-03,1165.270020,10172.139648,2044.270020,6266.310059,842.250000,NaN,495.510010,21.340000,5270.290039,4681.200195,...,NaN,727.659973,5526.299316,7774.200195,14265.0,6603.750000,1195.930054,340.600006,466.299988,NaN
2002-01-04,1172.510010,10259.740234,2059.379883,6307.970215,841.440002,NaN,499.299988,20.450001,5318.729980,4682.790039,...,NaN,747.719971,5638.508789,7833.200195,14332.0,6612.080078,1203.380005,343.220001,NaN,NaN
2002-01-07,1164.890015,10197.049805,2037.099976,6271.810059,837.330017,NaN,493.179993,21.940001,5232.220215,4615.540039,...,NaN,751.479980,5834.868164,7870.299805,14379.0,6565.439941,1188.949951,NaN,468.920013,NaN
2002-01-08,1160.709961,10150.549805,2055.739990,6235.430176,836.200012,NaN,497.899994,21.830000,5236.370117,4568.089844,...,NaN,734.760010,5810.058594,7782.000000,14168.0,6641.140137,1168.010010,NaN,460.779999,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-06-24,3050.330078,25445.939453,9909.169922,11726.540039,1949.699951,10371.440430,1389.739990,33.840000,12093.940430,4871.359863,...,11124.360352,2161.510010,11660.669922,15294.400391,94377.0,37908.378906,NaN,40435.339844,1348.689941,3116.879883
2020-06-25,3083.760010,25745.599609,10017.000000,11865.110352,1956.819946,10417.110352,1413.310059,32.220001,12177.870117,4918.580078,...,11129.230469,2112.370117,NaN,15446.099609,95983.0,37734.519531,NaN,41996.648438,1339.949951,3095.979980
2020-06-26,3009.050049,25015.550781,9757.219727,11604.429688,1911.760010,10440.040039,1378.780029,34.730000,12089.389648,4909.640137,...,NaN,2134.649902,NaN,15189.000000,93834.0,37431.949219,NaN,40589.890625,NaN,3067.770020
2020-06-29,3053.239990,25595.800781,9874.150391,11777.080078,1952.979980,10550.559570,1421.209961,31.780001,12232.120117,4945.459961,...,11422.099609,2093.479980,11542.620117,15389.700195,95735.0,37769.191406,NaN,40308.109375,1311.540039,3101.570068
2020-06-30,3100.290039,25812.880859,10058.769531,11893.780273,1993.150024,10457.589844,1441.369995,30.430000,12310.929688,4935.990234,...,11350.269531,2108.330078,11621.240234,15515.200195,95056.0,37716.429688,NaN,38686.691406,1324.130005,3104.169922

In [10]:
#missing values
master_data.isnull().sum()

^GSPC           0
^DJI            0
^IXIC           0
^NYA            0
^XAX            0
^BUK100P     2241
^RUT            0
^VIX            0
^GDAXI         82
^FCHI          48
^STOXX50E    1407
^N100          48
^BFX           49
IMOEX.ME     2901
^N225         279
^HSI          213
000001.SS     244
399001.SZ     245
^AXJO         535
^AORD         534
^BSESN        229
^JKSE         267
^NZ50        1262
^KS11         236
^TWII         256
^GSPTSE        79
^BVSP         197
^MXX          137
^IPSA         424
^MERV         254
^TA125.TA    1115
^JN0U.JO     3983
dtype: int64

In [11]:
#remove all indices with greater than 600 missing values
remove=['^BUK100P','^STOXX50E','IMOEX.ME','^NZ50','^TA125.TA','^JN0U.JO']
master_data=master_data.drop(columns=remove)

In [12]:
#forward filling the missing value
master_data=master_data.fillna(method='ffill')
master_data=master_data.dropna()
master_data.isnull().sum()

^GSPC        0
^DJI         0
^IXIC        0
^NYA         0
^XAX         0
^RUT         0
^VIX         0
^GDAXI       0
^FCHI        0
^N100        0
^BFX         0
^N225        0
^HSI         0
000001.SS    0
399001.SZ    0
^AXJO        0
^AORD        0
^BSESN       0
^JKSE        0
^KS11        0
^TWII        0
^GSPTSE      0
^BVSP        0
^MXX         0
^IPSA        0
^MERV        0
dtype: int64

In [ ]:
#cleaned master data export
master_data.to_csv('C:\\Users\\PC\\Desktop\\Thesis\\database\\thesis_data\\master_data_cleaned.csv')